### PR TITLE
Made Region options consistent

### PR DESCRIPTION
**Pull request by Raylehnhoff**
This commit removed OC from my local repo, but the declined PR from origin still has the select lists in an inconsistent order. This fixes that.

### CODE REVIEW

**Comment by bmagic** [comment]
We use the classical order from Warcraftlogs (https://www.warcraftlogs.com/ -> Menu Realms) and Wowprogress (homepage) 

Do you have any suggestion why we should put US in last position ?

**Comment by Raylehnhoff** [comment]
I ordered them alphabetically. Currently on the site there are two
different orderings for them. I don't much care what order they're in, as
long as they're consistent

**Comment by yz0** [comment]
Hi,

I just push #168. This should fix the problem.

Thanks for the report :)

**Comment by Raylehnhoff** [comment]
No problem! Closing!

**Pull request closed without merging**
