### PR TITLE
#120 - Adds a sort on character levels in the character list

### PR DESCRIPTION
**Pull request by Raylehnhoff**
Added a simple sort function on the characters array -- I'm not sure if you'd want to move this function somewhere else, but it sorts the list appropriately on the "Choose a character to add" list.

### CODE REVIEW

**Comment by Raylehnhoff** [comment]
Also after re-reading #120, I'm not sure if that's the appropriate issue. I don't see a bug report for the character list being ordered randomly, though.

**Comment by yz0** [comment]
Hello,

Character list (like guild list) are not ordered randomly :) It's sorted by the updated time of each ads. The "time ago" is written at the right of each ads vertically.

Peoples wants the possibility to sort by ilevel/progression and stuff like that (maybe alphabetical but i don't see the point).

Anyway it can't be done from the user side. This must be done from the server side for obvious reason !

**Comment by Raylehnhoff** [comment]
@yz0 The current character model doesn't have ilvl. When I pull back my characters the listing has my level-100s not even near the top of the list.

This ordering will, at the very least, produce a better user experience, even if it's added to down the road.

http://imgur.com/S7CsYml

**Comment by yz0** [comment]
Ok i'm retard :P

My bads, checking it again tomorrow after a good night will be better !

But it seems great, thanks :)

**Comment by Raylehnhoff** [comment]
No problem, glad to help.

**Comment by bmagic** [comment]
I fix it !!! But I use angularjs filter function.
https://github.com/warcraftlfg/warcraft-lfg/pull/170

**Comment by Raylehnhoff** [comment]
That works! I'm pretty new to angular, so I apologize for my lack of
framework depth on solutions like this.

**Pull request closed without merging**
