### PR TITLE
Fix legendary count

### PR DESCRIPTION
**Pull request by SnomeaD**
character.items is a key/value object, can't be looped that way.
(character.items.length is undefined)

### CODE REVIEW

**Comment by bmagic** [comment]
Thx !!! I will put it in prod now.

**Comment by bmagic** [comment]
It's live.

**Comment by SnomeaD** [comment]
Awesome! My guildy Hïei@sargeras got his legendary! 
Thanks for your dedication! I love what you've done!

**Comment by bmagic** [comment]
Tant mieux alors :)  On n'a pas cette chance dans notre guilde :(

**Pull request merged**
