### PR TITLE
Bmagic

### PR DESCRIPTION
**Pull request by bmagic**

### CODE REVIEW

**Comment by Raylehnhoff** [comment]
This commit seems to have re added http for the item lookups, which will
cause mixed content warnings.

**Comment by bmagic** [comment]
Yes because if you try with https Chrome & Firefox do not display the images for the media.blizzard.com domain ...

**Comment by Raylehnhoff** [comment]
Is there any reason to not bring those images into the project? Mixed
content warnings can cause them to get blocked by some browsers, too.

**Comment by bmagic** [comment]
No reason, it's a good idea.

**Pull request merged**
